# @package target
# IL3 target configuration

target_name: "itln2"
target_pdb_path: "pdbs/itln2.pdb"
# Ensure chains in PDB have the right chain IDs (ideally A, B, C, etc.)
target_chain: "A"
# binder chain should always be the last chain (e.g. "B" for 1 chain target, "C" for 2 chain target, "D" for 3 chain target, etc.)
binder_chain: "B"
target_hotspots: "A153,A200,A259"

# Residue to be used for Chai-1 distance constraint ({residue 1-letter}{res. num.}). 
# Can delete or set to None if no constraint. Residue should be in chain A
# hotspot_residue: "L13"

